#1171 do not allow emojis with unicode version larger than 9.0
elimu-ai/webapp pull request #1182
Opened 2021-01-02 14:40 UTC by cebr76

2021-01-03 10:26 UTC, nya-elimuai requested changes

2021-01-03 10:26 UTC, nya-elimuai commented on src/main/java/ai/elimu/web/content/emoji/EmojiCreateController.java
> +        if(emoji.getUnicodeVersion() > 9){
Add spacing before/after parenthesis: `if (emoji.getUnicodeVersion() > 9) {`

2021-01-03 10:26 UTC, nya-elimuai commented on src/main/webapp/WEB-INF/i18n/errors_en.properties
> +emoji.unicode.version=only emojis up to unicode version 9
Change from lower-case to upper-case: "Only"

2021-01-21 23:58 UTC, nya-elimuai requested changes
@cebr76 Looks great, thank you 🙂

Can you also add this code modification to the `EmojiEditController`?

2021-02-15 13:02 UTC, nya-elimuai approved these changes

2021-02-16 11:30 UTC, jo-elimuai commented on src/main/webapp/WEB-INF/i18n/errors_en.properties
> +emoji.unicode.version=Only emojis up to unicode version 9
```suggestion
emoji.unicode.version=Only emojis up to Unicode version 9
```

2021-02-16 11:30 UTC, jo-elimuai approved these changes

2021-02-16 11:42 UTC, nya-elimuai approved these changes

2021-02-16 11:42 UTC, merged

2021-02-16 11:43 UTC, nya-elimuai commented
@cebr76 Your changes have been incorporated into the `master` branch. Thank you for contributing 🙂