[#1401] Skip Edit Contribution Page for localhost development
elimu-ai/webapp pull request #1494
Opened 2022-01-22 19:06 UTC by eymaal

This PR adds a condition in `MainContentController` to redirect to `/content/contributor/edit-motivation` only if the environment isn't `dev`.
This way localhost environments do not redirect to the Edit Motivation page on logging in.

Do let me know if you would rather prefer for the condition to be extracted into a separate function `isContributorADeveloper()` in a new Utils class/`EnvironmentContextLoaderListener` for better readability.

2022-01-22 19:43 UTC, nya-elimuai requested changes
@eymaal Looks good 👍🏽

Just added some minor formatting for readability. Once you approve it, we can merge.

2022-01-22 19:43 UTC, nya-elimuai commented on src/main/java/ai/elimu/web/content/MainContentController.java
> +        } else if (StringUtils.isBlank(contributor.getMotivation()) && EnvironmentContextLoaderListener.env!=Environment.DEV) {
```suggestion
        } else if (StringUtils.isBlank(contributor.getMotivation()) && (EnvironmentContextLoaderListener.env != Environment.DEV)) {
```

2022-01-22 20:07 UTC, nya-elimuai commented
@Shubham-Vishwakarma ☝🏽

2022-01-23 06:03 UTC, eymaal commented
@nya-elimuai I'm made the formatting changes. Thank you.

2022-01-23 08:36 UTC, nya-elimuai approved these changes
Looks good 👍🏽

Ready to be merged.

2022-01-23 08:38 UTC, nya-elimuai commented
@eymaal Note that after you merge the branch, the changes will be deployed to http://hin.test.elimu.ai so that you can test your changes there.

2022-01-23 08:38 UTC, merged

2022-01-23 09:37 UTC, eymaal commented
@nya-elimuai  

- [ ] Verified that the edit-motivation screen is not skipped on the Test environment.