1589 Problem with load data during startup application on windows
elimu-ai/webapp pull request #1590
Opened 2022-07-17 15:22 UTC by tomaszsmy

2022-07-19 14:51 UTC, nya-elimuai approved these changes

2022-07-24 02:13 UTC, nya-elimuai requested changes
Added a small refactoring suggestion.

2022-07-24 02:13 UTC, nya-elimuai commented on src/main/java/ai/elimu/util/db/DbContentImportHelper.java
> +
```suggestion
```

2022-07-24 02:13 UTC, nya-elimuai commented on src/main/java/ai/elimu/util/db/DbContentImportHelper.java
> +        String contentDirectoryPath = "db" + SLASH + "content_" + environment + SLASH + language.toString().toLowerCase();
```suggestion
        String contentDirectoryPath = "db/content_" + environment + "/" + language.toString().toLowerCase();
```

2022-07-24 02:13 UTC, nya-elimuai commented on src/main/java/ai/elimu/util/db/DbContentImportHelper.java
> +        String analyticsDirectoryPath = "db" + SLASH + "analytics_" + environment + SLASH + language.toString().toLowerCase();
```suggestion
        String analyticsDirectoryPath = "db/analytics_" + environment + "/" + language.toString().toLowerCase();
```

2022-07-25 02:58 UTC, nya-elimuai approved these changes
Ready to be merged 🙂

2022-08-06 11:13 UTC, tomaszsmy commented
> 



> Ready to be merged 🙂

remote: error: At least 2 approving reviews are required by reviewers with write access.

2022-08-06 13:29 UTC, jo-elimu approved these changes

2022-08-06 13:29 UTC, merged