#1600 Include Windows OS in continuous integration
elimu-ai/webapp pull request #1601
Opened 2022-07-21 01:09 UTC by jo-elimu

close #1600

2022-07-21 08:20 UTC, hhio618 requested changes
There are so many errors, like this one:
```
2022-07-21T01:13:37.1411967Z Caused by: java.sql.SQLSyntaxErrorException: object name already exists: AUDIOCONTRIBUTIONEVENT in statement [create table AudioContributionEvent (id bigint generated by default as identity (start with 1), comment varchar(1000), platform varchar(255), revisionNumber integer, time timestamp, timeSpentMs bigint, contributor_id bigint, audio_id bigint, primary key (id))]
2022-07-21T01:13:37.1412230Z 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.6.1.jar:2.6.1]
2022-07-21T01:13:37.1412479Z 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.6.1.jar:2.6.1]
2022-07-21T01:13:37.1412743Z 	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[hsqldb-2.6.1.jar:2.6.1]
2022-07-21T01:13:37.1413108Z 	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source) ~[hsqldb-2.6.1.jar:2.6.1]
2022-07-21T01:13:37.1413444Z 	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar:1.4]
2022-07-21T01:13:37.1414059Z 	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264) ~[commons-dbcp-1.4.jar:1.4]
2022-07-21T01:13:37.1414706Z 	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54) ~[hibernate-core-5.5.7.Final.jar:5.5.7.Final]
2022-07-21T01:13:37.1414759Z 	... 99 more
```

2022-07-21 10:42 UTC, nya-elimuai approved these changes

2022-07-21 10:53 UTC, jo-elimu commented
@hhio618 Thanks for pointing that out. It should be fixed now: https://github.com/elimu-ai/webapp/pull/1601/commits/469b0fc36c6036e2606e05511e4b071b8296351f

2022-07-22 07:23 UTC, nya-elimuai commented
@tomaszsmy @vrudas Could you help review this, please? 🙂

2022-07-22 14:49 UTC, tomaszsmy approved these changes

2022-07-24 01:56 UTC, merged