1678 Rename from time to timestamp in the database
elimu-ai/webapp pull request #1738
Opened 2024-07-15 18:07 UTC by alexander-kuruvilla

Closes #1678 

Changes:
Updated the name of objects name time to timestamp.
Updated setTime() to setTimestamp().
Updated getTime() to getTimestamp().
Updated references to getters and setters in the code.

2024-07-16 03:47 UTC, jo-elimu requested changes
Thank you, @alexander-kuruvilla. Note that the webapp is already running in production, so we need to update the underlying database structure whenever we modify the JPA entities.

So your changes in `jpa-schema-export.sql` would have to be reflected in a database migration script. See more info here: https://github.com/elimu-ai/webapp/blob/main/DB_MIGRATION.md

---

FYI, these are the tables that would have to be migrated:

```sql
MariaDB [webapp-HIN]> SHOW TABLES LIKE '%Event';
+-------------------------------+
| Tables_in_webapp-HIN (%Event) |
+-------------------------------+
| AudioContributionEvent        |
| AudioPeerReviewEvent          |
| ImageContributionEvent        |
| LetterContributionEvent       |
| LetterLearningEvent           |
| LetterSoundContributionEvent  |
| LetterSoundPeerReviewEvent    |
| NumberContributionEvent       |
| NumberPeerReviewEvent         |
| SoundContributionEvent        |
| StoryBookContributionEvent    |
| StoryBookLearningEvent        |
| StoryBookPeerReviewEvent      |
| WordContributionEvent         |
| WordLearningEvent             |
| WordPeerReviewEvent           |
+-------------------------------+
16 rows in set (0.001 sec)
```

And here is an example of what a table currently looks like:

```sql
MariaDB [webapp-HIN]> DESCRIBE LetterLearningEvent;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| id                | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| androidId         | varchar(255) | NO   |     | NULL    |                |
| time              | datetime     | NO   |     | NULL    |                |
| learningEventType | varchar(255) | NO   |     | NULL    |                |
| letterText        | varchar(255) | NO   |     | NULL    |                |
| application_id    | bigint(20)   | YES  | MUL | NULL    |                |
| letter_id         | bigint(20)   | YES  | MUL | NULL    |                |
| packageName       | varchar(255) | NO   |     | NULL    |                |
+-------------------+--------------+------+-----+---------+----------------+
8 rows in set (0.001 sec)
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/model/analytics/LearningEvent.java
> +    public void setTimestamp(Calendar time) {
```suggestion
    public void setTimestamp(Calendar timestamp) {
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/model/contributor/ContributionEvent.java
> +        this.timestamp = time;
```suggestion
    public void setTimestamp(Calendar timestamp) {
        this.timestamp = timestamp;
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/model/contributor/PeerReviewEvent.java
> +        this.timestamp = time;
```suggestion
        this.timestamp = timestamp;
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/rest/v2/analytics/LetterLearningEventsRestController.java
> +                letterLearningEvent.setTimestamp(time);
```suggestion
                letterLearningEvent.setTimestamp(timestamp);
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/rest/v2/analytics/StoryBookLearningEventsRestController.java
> +                storyBookLearningEvent.setTimestamp(time);
```suggestion
                storyBookLearningEvent.setTimestamp(timestamp);
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/rest/v2/analytics/WordLearningEventsRestController.java
> +                wordLearningEvent.setTimestamp(time);
```suggestion
                wordLearningEvent.setTimestamp(timestamp);
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/java/ai/elimu/util/csv/CsvAnalyticsExtractionHelper.java
> +                storyBookLearningEvent.setTimestamp(time);
```suggestion
                storyBookLearningEvent.setTimestamp(timestamp);
```

2024-07-16 03:47 UTC, jo-elimu commented on src/main/resources/META-INF/jpa-schema-export.sql
> +        timestamp datetime,
A database migration script is missing for this file.

2024-07-16 14:40 UTC, alexander-kuruvilla commented
@jo-elimu thanks for your guidance and input, I will work on those.

2024-07-17 06:22 UTC, jo-elimu requested changes
@alexander-kuruvilla The changes need to be reflected in the frontend files as well. For example the `WEB-INF/jsp/content/letter/edit.jsp`:

```java
Caused by: javax.el.PropertyNotFoundException: Property [time] not found on type [ai.elimu.model.contributor.LetterContributionEvent]
    at javax.el.BeanELResolver$BeanProperties.get (BeanELResolver.java:253)
    at javax.el.BeanELResolver$BeanProperties.access$300 (BeanELResolver.java:206)
    at javax.el.BeanELResolver.property (BeanELResolver.java:322)
    at javax.el.BeanELResolver.getValue (BeanELResolver.java:93)
    at org.apache.jasper.el.JasperELResolver.getValue (JasperELResolver.java:125)
    at org.apache.el.parser.AstValue.getValue (AstValue.java:168)
    at org.apache.el.ValueExpressionImpl.getValue (ValueExpressionImpl.java:189)
    at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate (PageContextImpl.java:690)
    at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspx_meth_fmt_005fformatDate_005f0 (edit_jsp.java:1411)
    at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspx_meth_c_005fforEach_005f0 (edit_jsp.java:1305)
    at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspx_meth_content_005fsection_005f0 (edit_jsp.java:365)
    at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspService (edit_jsp.java:227)
```

<kbd>![](https://github.com/user-attachments/assets/b738c824-05d3-432f-bd02-258674283b7b)</kbd> --> <kbd>![](https://github.com/user-attachments/assets/9f2a3489-30ec-444c-9719-f570509473ad)</kbd>

> [!TIP]
> For a quick sign-on during localhost development, use this URL: http://localhost:8080/webapp/sign-on/test/role-CONTRIBUTOR

2024-07-17 06:31 UTC, alexander-kuruvilla commented
> @alexander-kuruvilla The changes need to be reflected in the frontend files as well. For example the `WEB-INF/jsp/content/letter/edit.jsp`:
> 
> ```java
> Caused by: javax.el.PropertyNotFoundException: Property [time] not found on type [ai.elimu.model.contributor.LetterContributionEvent]
>     at javax.el.BeanELResolver$BeanProperties.get (BeanELResolver.java:253)
>     at javax.el.BeanELResolver$BeanProperties.access$300 (BeanELResolver.java:206)
>     at javax.el.BeanELResolver.property (BeanELResolver.java:322)
>     at javax.el.BeanELResolver.getValue (BeanELResolver.java:93)
>     at org.apache.jasper.el.JasperELResolver.getValue (JasperELResolver.java:125)
>     at org.apache.el.parser.AstValue.getValue (AstValue.java:168)
>     at org.apache.el.ValueExpressionImpl.getValue (ValueExpressionImpl.java:189)
>     at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate (PageContextImpl.java:690)
>     at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspx_meth_fmt_005fformatDate_005f0 (edit_jsp.java:1411)
>     at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspx_meth_c_005fforEach_005f0 (edit_jsp.java:1305)
>     at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspx_meth_content_005fsection_005f0 (edit_jsp.java:365)
>     at org.apache.jsp.WEB_002dINF.jsp.content.letter.edit_jsp._jspService (edit_jsp.java:227)
> ```
> 
> ![](https://private-user-images.githubusercontent.com/1451036/349383102-b738c824-05d3-432f-bd02-258674283b7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTc4MzQsIm5iZiI6MTcyMTE5NzUzNCwicGF0aCI6Ii8xNDUxMDM2LzM0OTM4MzEwMi1iNzM4YzgyNC0wNWQzLTQzMmYtYmQwMi0yNTg2NzQyODNiN2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMDYyNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWI4Y2Y5MDIxNDRlMGY0MTEyYzE5YTRmMDZhMmM4ODVmYWI5YjAyZTQyNWM0NjFlZmQ3YWJlZmIwZTM5OTQxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wk1-fxsQe9LqFhC9Joc_ua_HxUaH8PLapd8zUaM1sBM) --> ![](https://private-user-images.githubusercontent.com/1451036/349383297-9f2a3489-30ec-444c-9719-f570509473ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTc4MzQsIm5iZiI6MTcyMTE5NzUzNCwicGF0aCI6Ii8xNDUxMDM2LzM0OTM4MzI5Ny05ZjJhMzQ4OS0zMGVjLTQ0NGMtOTcxOS1mNTcwNTA5NDczYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMDYyNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM2YmNjYzliZTc3MDZiNWMzODhhYzcxYWMzODA3MzkzMzI2MGExODkxZmJiNjFhYWUxOGI3MDA2ZTkyYTk5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bwvuCCqH7f_-SF8FYYTQYGuW4mH4Z1Q5l3DYPrfiEyw)
> 
> Tip
> 
> For a quick sign-on during localhost development, use this URL: http://localhost:8080/webapp/sign-on/test/role-CONTRIBUTOR

Got it. I wasn't able to check out the frontend, thanks for that tip. I'll update the jsps and go over the pages. Thanks.

Also I wanted to run something by you regarding coderabbitai's query optimisation suggestion, should I make the changes along with this or does that have to be another issue?

2024-07-17 09:19 UTC, jo-elimu commented on src/main/java/ai/elimu/dao/jpa/LetterSoundContributionEventDaoJpa.java
> +            "ORDER BY e.timestamp ASC")
@coderabbitai Yes, please.

2024-07-17 11:20 UTC, jo-elimu approved these changes
Looks ready to merge 🙂

2024-07-17 11:26 UTC, merged